server:
  servlet:
    session:
      cookie:
        name: KSESSION
  port: 8084

spring:
   application: 
     name: SHOPPING-CART
   datasource:
       url: jdbc:mysql://localhost:3306/shopping-cart-service-dba?serverTimezone=UTC
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver
   jpa:
     hibernate:
      
       naming:
         implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     properties:
       hibernate: 
         show_sql: true
         use_sql_comments: true
         format_sql: true 
            
security:
  oauth2:
    client:
      client-id: shopping-cart-service
      client-secret: pass
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://localhost:8282/oauth/token
      scope: READ,WRITE
      auto-approve-scopes: '.*'
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
     

       

logging:
  file: 
    name: C:\ELK\logs\microservice-app.log
#  level:
 #   org:
  #    hibernate:
   #     type: trace
  
        