server:
  servlet:
    context-path: /payments-api
    session:
      cookie:
        name: KSESSION
  port: ${PAYMENT_SERVICE_PORT}

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/saga_orchestration_payment_service_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

security:
  oauth2:
    client:
      client-id: payment-service
      client-secret: pass
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://localhost:8282/oauth/token
      scope: READ,WRITE
      auto-approve-scopes: '.*'
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token

logging:
  file:
    name: C:\ELK\logs\microservice-app.log