server:
    servlet:
     session:
      cookie:
        name: KSESSION
    port: 8083
   
spring:
   application: 
     name: PRODUCT-SERVICE
   datasource:
       url: jdbc:mysql://localhost:3306/product-service-dba?serverTimezone=UTC
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver
   jpa:     hibernate:       naming:         implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     properties:
       hibernate: 
         show_sql: true
         use_sql_comments: true
         format_sql: true

logging:
  file: 
    name: C:\ELK\logs\microservice-app.log # level:  #  org:
   #   hibernate:
   #     type: trace

security:
  oauth2:
    client:
      client-id: product-service
      client-secret: pass
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://localhost:8282/oauth/token
      scope: READ,WRITE
      auto-approve-scopes: '.*'
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
       