server:
  port: ${OAUTH_SERVER_PORT}

spring:
  application:
    name: OAUTH-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:${OAUTH_SERVER_PORT}/oauth2/userinfo

logging:
  level:
    org:
      hibernate:
        type: trace