package fon.master.nst.mailservice.model;

public enum OrderStatus {
    
    CREATED, PRODUCT_OUT_OF_STOCK, PRODUCT_RESERVED, CUSTOMER_PAYMENT_PREPARED, CUSTOMER_INCOMPLETE_DATA, PAYMENT_SUCCESSFUL, PAYMENT_OUT_OF_MONEY, FAILED, PRODUCT_FAILED, CUSTOMER_FAILED, PAYMENT_FAILED, MAIL_SENT, MAIL_FAILED

}
